export const autoComplete = [{
    title: 'Karkhana',
    item: 'Movie'
},
{ title: 'Sushil Shrestha', item: 'Actor' },
{ title: 'Nabin Lamsal', item: 'Actor' },
{ title: 'Mausami Malla', item: 'Actor' },
{ title: 'Barsha Siwakoti', item: 'Actor' },
{ title: 'Jebica Karki', item: 'Actor' },
{ title: 'Dui Rupaiyaa', item: 'Song' },
{ title: 'Kutu Ma Kutu', item: 'Song' },
{ title: 'Talkyo Jawani', item: 'Song' },
{ title: 'Pashupati Prasad', item: 'Actor' },
{ title: 'Khagendra Lamichhane', item: 'Actor' },
{ title: 'Rabindra Singh Baniya', item: 'Actor' },
{ title: 'Bipin Karki', item: 'Actor' },
{ title: 'Barsha Siwakoti', item: 'Actor' },
{ title: 'Prakash Ghimire', item: 'Actor' },
{ title: 'Talakjung vs Tulke', item: 'Movie' },
{ title: 'Prakash Ghimire', item: 'Actor' },
{ title: 'Reecha Sharma', item: 'Actor' },
{ title: 'Rabindra Singh Baniya', item: 'Actor' },
{ title: 'Shushank Mainali', item: 'Actor' },
{ title: 'Buddhi Tamang', item: 'Actor' },
{ title: 'Dayahang Rai', item: 'Actor' },
{ title: 'Sunkesari', item: 'Movie' },
{ title: 'Lauren Lofberg', item: 'Actor' },
{ title: 'Rabindra Jha', item: 'Actor' },
{ title: 'Bhim Neupane', item: 'Actor' },
{ title: 'Sunny Dhakal', item: 'Actor' },
{ title: 'Amy Parajuli', item: 'Actor' },
{ title: 'Prerana Thapa', item: 'Actor' },
{ title: 'Tamanna Sharma', item: 'Actor' },
{ title: 'Loot', item: 'Movie' },
{ title: 'Karma Shakya', item: 'Actor' },
{ title: 'Prateek Raj Neupane', item: 'Actor' },
{ title: 'Saugat Malla', item: 'Actor' },
{ title: 'Sushil Raj Pandey', item: 'Actor' },
{ title: 'Praween Khatiwada', item: 'Actor' },
{ title: 'Srijana Subba', item: 'Actor' },
{ title: 'White Sun', item: 'Movie' },
{ title: 'Asha Maya Magrati', item: 'Actor' },
{ title: 'Sumi Malla', item: 'Actor' },
{ title: 'Amrit Pariyar', item: 'Actor' },
{ title: 'Sarada Adhikari', item: 'Actor' },
{ title: 'Chhadke', item: 'Movie' },
{ title: 'Namrata Shrestha', item: 'Actor' },
{ title: 'Arpan Thapa', item: 'Actor' },
{ title: 'Aruna Karki', item: 'Actor' },
{ title: 'Sambodhan', item: 'Movie' },
{ title: 'Prasant Tamrakar', item: 'Actor' },
{ title: 'Binay Bhatt', item: 'Actor' },
{ title: 'B.S. Rana', item: 'Actor' },
{ title: 'Kabir Khadka', item: 'Actor' },
{ title: 'Sano Sansar', item: 'Actor' },
{ title: 'Neer Bikram Shah', item: 'Actor' },
{ title: 'Jiwan Luitel', item: 'Actor' },
{ title: 'Vinay Shrestha', item: 'Actor' },
{ title: 'Sushila Raimajhi', item: 'Actor' },
{ title: 'Basudev', item: 'Movie' },
{ title: 'Harihar Sharma', item: 'Actor' },
{ title: 'Sharmila Malla', item: 'Actor' },
{ title: 'Hari Bansha Acharya', item: 'Actor' },
{ title: 'Madan Krishna Shrestha', item: 'Actor' }];